### ISSUE TITLE
jdbc-ajurin lataaminen ei onnistu

### ISSUE THREAD

**Issue by markusbattarbee** [Roadstar/Tilitin#1]
Hei,
kiitos että olet pyrkinyt auttamaan tilittimen käytössä moderneillakin distroilla. Java-maailma ei ole tuttu, mutta siis:
Käytössä on Macbook Air M2, macOS Ventura 13.3. 
Asensin `homebrew`:lla javan (openjdk 20)
```
openjdk 20 2023-03-21
OpenJDK Runtime Environment Homebrew (build 20)
OpenJDK 64-Bit Server VM Homebrew (build 20, mixed mode, sharing)
```
imuroin tämän repon ja yritys käynnistää seuraavanlaisella komennolla antaa virheilmon:
```
$ java -classpath "./lib/;sqlite-jdbc-3.8.10.1.jar" -jar TilitinArm.jar
Apr 10, 2023 8:31:05 PM kirjanpito.ui.DocumentFrame openDataSource
SEVERE: Tietokantayhteyden avaaminen epäonnistui
kirjanpito.db.DataAccessException: Error opening connection
	at kirjanpito.db.sqlite.SQLiteDataSource.open(SQLiteDataSource.java:73)
	at kirjanpito.db.DataSourceFactory.create(DataSourceFactory.java:38)
	at kirjanpito.models.DocumentModel.openDataSource(DocumentModel.java:98)
	at kirjanpito.ui.DocumentFrame.openDataSource(DocumentFrame.java:2123)
	at kirjanpito.ui.Kirjanpito.run(Kirjanpito.java:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.sql.SQLException: Error opening connection
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:213)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:74)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
	at kirjanpito.db.sqlite.SQLiteDataSource.open(SQLiteDataSource.java:62)
	... 17 more
Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:284)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:65)
	at org.sqlite.core.NativeDB.load(NativeDB.java:53)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:209)
	... 26 more
```
eli tuo repon mukana tullut jdbc-ajuri ei ilmeisesti suostu latautumaan. Kokeilin hakea myös https://github.com/xerial/sqlite-jdbc jdbc-ajuria mutta eipä sekään onnistunut. Onko ehdotuksia?

**Comment by Roadstar** [comment]
Virheilmoituksen perusteella ajuri ei löydä kelvollista alustatargettia. En ole itse tarvinnut Tilitintä nyt vähään aikaan niin ei ole tullut tarkistettua toimivuutta macOS:n tuoreimmilla versioilla. Tuon linkatun xerialin ajurin pitäisi periaatteessa toimia, mutta pitääkin ihmetellä tuota aikataulujen salliessa.

**Comment by Roadstar** [comment]
Otin käyttöön xerialin ajurin ja nyt softa käynnistyy ainakin M1 MacBook Airilla Ventura 13.3.1:llä. Tuossa on huomattava se, että siinä hakemistossa, mistä TilitinArm.jar ajetaan pitää olla Tilikarttamalllit-alihakemisto, jotta alussa on valittavana eri tilikarttamallit.
